# Generated by Django 5.0.4 on 2024-05-12 04:20

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peticionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llegada', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_radicado', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('radicado', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('ciudad', models.CharField(choices=[('Bogota', 'Bogotá D.C'), ('Funza', 'Funza')], max_length=50)),
                ('localidad', models.CharField(choices=[('Usaquén', 'Usaquén'), ('Chapinero', 'Chapinero'), ('Santa Fe', 'Santa Fe')], max_length=50)),
                ('barrio', models.CharField(max_length=50)),
                ('tipo_dp', models.CharField(choices=[('Queja', 'Queja'), ('Solicitud', 'Solicitud')], max_length=50)),
                ('tema_dp', models.CharField(choices=[('Ruido', 'Ruido'), ('Altitud', 'Altitud'), ('Rutas', 'Rutas'), ('Ruido, rutas y altitud', 'Ruido, rutas y altitud'), ('Insonorizacion', 'Insonorizacion'), ('Eventos Aeronauticos', 'Eventos Aeronauticos'), ('Eventos especificos', 'Eventos especificos'), ('Otros', 'Otros')], max_length=50)),
                ('asunto', models.TextField(blank=True, max_length=500)),
                ('peticion', models.TextField(blank=True, max_length=500)),
                ('enviada', models.BooleanField(default=False)),
                ('radicado_salida', models.CharField(max_length=50)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'peticionario',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=app.models.ruta_archivo)),
                ('peticionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.peticionarios')),
            ],
        ),
    ]
