# Generated by Django 5.0.4 on 2024-05-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticionarios',
            name='barrio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('Bogota', 'Bogotá D.C'), ('Funza', 'Funza')], max_length=50),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='latitud',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='localidad',
            field=models.CharField(blank=True, choices=[('Usaquén', 'Usaquén'), ('Chapinero', 'Chapinero'), ('Santa Fe', 'Santa Fe')], max_length=50),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='longitud',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='radicado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='radicado_salida',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='tema_dp',
            field=models.CharField(blank=True, choices=[('Ruido', 'Ruido'), ('Altitud', 'Altitud'), ('Rutas', 'Rutas'), ('Ruido, rutas y altitud', 'Ruido, rutas y altitud'), ('Insonorizacion', 'Insonorizacion'), ('Eventos Aeronauticos', 'Eventos Aeronauticos'), ('Eventos especificos', 'Eventos especificos'), ('Otros', 'Otros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='tipo_dp',
            field=models.CharField(blank=True, choices=[('Queja', 'Queja'), ('Solicitud', 'Solicitud')], max_length=50),
        ),
    ]
