# Generated by Django 5.0.4 on 2024-05-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_peticionarios_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticionarios',
            name='localidad',
            field=models.CharField(blank=True, choices=[('Barrios Unidos', 'Barrios Unidos'), ('Usaquén', 'Usaquén'), ('Fontibón', 'Fontibón'), ('Engativa', 'Engativa'), ('Teusaquillo', 'Teusaquillo'), ('Funza', 'Funza'), ('Suba', 'Suba')], max_length=50),
        ),
    ]
