# Generated by Django 5.0.4 on 2024-05-21 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_peticionarios_localidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='RtasFinales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rta', models.FileField(upload_to='rtas/')),
                ('peticionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.peticionarios')),
            ],
        ),
    ]
