# Generated by Django 5.0.4 on 2024-05-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rtasfinales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticionarios',
            name='asunto',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='peticion',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='radicado',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='radicado_salida',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
