# Generated by Django 5.0.4 on 2024-05-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_peticionarios_asunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticionarios',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('Bogotá D.C.', 'Bogotá D.C.'), ('Funza', 'Funza')], max_length=50),
        ),
    ]
