# Generated by Django 5.0.4 on 2024-06-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_peticionarios_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticionarios',
            name='enviada_aerocivil',
            field=models.BooleanField(default=False),
        ),
    ]
