# Generated by Django 5.0.4 on 2024-07-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_peticionarios_enviada_aerocivil'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticionarios',
            name='enviada_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='localidad',
            field=models.CharField(blank=True, choices=[('Barrios Unidos', 'Barrios Unidos'), ('Usaquén', 'Usaquén'), ('Fontibón', 'Fontibón'), ('Engativa', 'Engativa'), ('Teusaquillo', 'Teusaquillo'), ('Funza', 'Funza'), ('Suba', 'Suba'), ('Kennedy', 'Kennedy'), ('Bosa', 'Bosa'), ('Ciudad Bolivar', 'Ciudad Bolivar'), ('Soacha', 'Soacha')], max_length=50),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='tema_dp',
            field=models.CharField(blank=True, choices=[('Ruido', 'Ruido'), ('Altitud', 'Altitud'), ('Rutas', 'Rutas'), ('Ruido, rutas y altitud', 'Ruido, rutas y altitud'), ('Insonorizacion', 'Insonorizacion'), ('Vibraciones', 'Vibraciones'), ('Solicitud Información', 'Solicitud Información'), ('Eventos especificos', 'Eventos especificos'), ('Otros', 'Otros')], max_length=50),
        ),
    ]
