# Generated by Django 5.0.4 on 2024-12-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_peticionarios_enviada_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticionarios',
            name='enviada_preliminar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peticionarios',
            name='localidad',
            field=models.CharField(blank=True, choices=[('Barrios Unidos', 'Barrios Unidos'), ('Usaquén', 'Usaquén'), ('Fontibón', 'Fontibón'), ('Engativa', 'Engativa'), ('Teusaquillo', 'Teusaquillo'), ('Funza', 'Funza'), ('Suba', 'Suba'), ('Kennedy', 'Kennedy'), ('Los Mártires', 'Los Mártires'), ('Bosa', 'Bosa'), ('SantaFe', 'SantaFe'), ('Ciudad Bolivar', 'Ciudad Bolivar'), ('Soacha', 'Soacha')], max_length=50),
        ),
    ]
